### ISSUE TITLE
Should this be `(A->B (A x))`?

### ISSUE THREAD

**Issue by gshen42** [lovrosdu/klor#2]
https://github.com/lovrosdu/klor/blob/991c9ad5867ef85c1d09e50b2f0090fb30257603/doc/tutorial-02-basics.md?plain=1#L134

`x` is at `A`, right?

**Comment by lovrosdu** [comment]
Hi Gan! :-)

`x` is logically indeed at `A` but the code is not a typo, since it's used as an example for the sentence just preceding it: "Klor won't complain if you use a role expression anyway, even if the role doesn't match the actual location of the argument".

In other words, that specific example is there to illustrate the purpose and a technical point of role expressions. Their function is not to change the location of an existing value but to modify the lifting rule of Klor's type system. The lifting rule has no effect on anything other than mentioned Clojure vars and literals, so `(B x)` does not affect the location of `x` in any way.

**Comment by gshen42** [comment]
I see. I missed the preceeding sentence. Thanks!
